<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Admin UI</title>
	</head>

	<body>
		<br>
			<form method="post" action="manageUsers.jsp">
			  	<input type="submit" value="Add, Edit information and Delete a customer representative or customer">
			</form><br>
			<form method="post" action="salesReport.jsp">
			  	<input type="submit" value="Obtain a sales report for a particular month">
			</form><br>
			<form method="post" action="reservationList.jsp">
			  	<input type="submit" value="Produce a list of reservations by flight number or by customer name">
			</form><br><br>
			<form method="post" action="revenueSum.jsp">
			Input any number of the below parameters as needed.<br>
				<label for="flightNumber">Flight Number:</label><br>
		 		<input type="text" id="flightNumber" name="flightNumber"><br>
				<label for="airline">Airline ID:</label><br>
		 		<input type="text" id="airline" name="airline"><br>
		 		<label for="cid">Customer ID:</label><br>
		 		<input type="text" id="cid" name="cid"><br>
			  	<input type="submit" value="Produce a summary listing of revenue generated by a particular flight, airline, or customer">
			</form><br><br>
			<form method="post" action="revenueCstm.jsp">
			  	<input type="submit" value="Find out which customer generated most total revenue">
			</form><br><br>
			<form method="post" action="mostTickets.jsp">
			  	<input type="submit" value="Produce a list of most active flights (most tickets sold)">
			</form>	
		<br>
		
	<% HttpSession ses = request.getSession();
		String errorMessage = (String) ses.getAttribute("Could not load page");
       if (errorMessage != null) { %>
        <p style="color: red;"><%= errorMessage %></p>
    <% } %>
	</body>
</html>